### ISSUE TITLE
Support for connectionString

### ISSUE THREAD

**Issue by PaulKiddle** [ThomWright/postgres-migrations#14]
Hello, thank you for this nice looking project, it seems to be perfect for what I need.

I would like to be able to use a [connectionString](https://node-postgres.com/features/connecting#connection-uri) in the config object, but the migrate function is a little too strict on its validation.

It would also be nice to be able to use `node-postgres`'s default config values but this is not currently possible, for the same reason.

**Comment by ThomWright** [comment]
Solved by c246ad3 and ad81ed9 #29

**Comment by nathanfranke** [comment]
I would like to have connectionString and ensure database exists, it would probably require parsing the URI though.
