### ISSUE TITLE
Hash sql generated by js files, not the files themselves

### ISSUE THREAD

**Issue by NeonPaul** [ThomWright/postgres-migrations#15]
Current method is inconsistent, as .js files may import external files which are not included in the hash, which could change the SQL statement without changing the hash.

This change would also allow e.g. linters to clean up a migration .js file after the migration has run.

**Comment by ThomWright** [comment]
Seems reasonable! I'd accept a PR for this, but it's a breaking change so would be a major version bump.

**Comment by ThomWright** [comment]
```js
const contents = await getFileContents(filePath)
const sql = getSqlStringLiteral(filePath, contents, type)
const hash = hashString(fileName + sql)
```

^ Like this?

I think this would maintain backwards compatibility for anyone only using `sql` files and not `js` files.

**Comment by pellicceama** [comment]
Correct. There's no way to make this backwards compatible for JS. But
should sove the issue.

**Comment by pellicceama** [comment]
Cool - Will make one!
