### ISSUE TITLE
Migration lock?

### ISSUE THREAD

**Issue by tom-drake** [ThomWright/postgres-migrations#23]
If I'm deploying a service with multiple instances, I think it would be good to have some kind of locking so that two instances can't try to run the same migration at the same time. It would probably be fine as the transaction would succeed on one instance and then fail on the second but it would be good to do this without any instances throwing an error.

I was thinking of something along the lines of
```sql
LOCK TABLE migrations IN ACCESS EXCLUSIVE MODE;
```

I'll throw a PR together.

**Comment by ThomWright** [comment]
@tanuck

This seems like a good idea! We've had several occasions where multiple instances of the same service have deployed and tried to run migrations simultaneously. Like you say, it was fine because one of them simply rolled back the transaction, but we did see errors.

**Comment by ThomWright** [comment]
Might be worth waiting until #22 is merged, since all the code will soon be in TypeScript.

**Comment by tom-drake** [comment]
I had a look at what was involved with this last night. It looks like the runMigration function will need a small refactor as I was hitting eslints max statements warning.

I'll walk through the logic for what I think is needed. I'm not sure what we can do when a user decides to run without a transaction as the lock requires one so I'll ignore that case.
1. Begin transaction
2. Attempt to take a lock on the migrations table
3. Check if the migration you want to run has already been run. This one is important as instances won't know the progress of the other instances. Each instance will take the lock and check in turn.
4. Run the migration if not already run.
5. End transaction

**Comment by tom-drake** [comment]
I've been working my way through this and had a question as it could make the migration code with locking a little easier. To take a lock out we need the table to exist so we can't take a lock out on the creation of the migration table as it doesn't exist yet. So I'm wondering if it makes sense to create the migration table as part of the migration set?

I think it would be a good idea to automatically create it as part of `fetchAppliedMigrationFromDB` if we don't find the migration table. Thoughts?

**Comment by ThomWright** [comment]
Hi @tom-drake 

Creating the `migrations` table as part of `fetchAppliedMigrationFromDB` seems like a strange side-effect to me, in a function that one would expect to be read-only.

I've written some notes up on two possible ways to implement this. I'm leaning away from an `ACCESS EXCLUSIVE` lock and towards using [advisory locks](https://www.postgresql.org/docs/9.6/explicit-locking.html#ADVISORY-LOCKS).

# Locking

## Table lock vs Advisory lock

- `ACCESS EXCLUSIVE` lock on `migrations` table inside a transaction
  - \+ enforced by Postgres
  - \- need to take out a lock for every migration
  - \- more complex?
  - \- not possible for migrations with transaction disabled*
  - \- needs special case for zeroth migration (creating `migrations` table)
- Advisory lock for the session
  - \+ single lock for entire duration of multiple migrations
  - \+ might be simpler logic and less refactoring?
    - `runMigration` can stay the same?
  - \+ works for migrations with transaction disabled
  - \+ Rails takes this approach
  - \- enforced by application
  - \- might break some configurations of PgBouncer:
    - Session pooling: fine
    - Transaction pooling: broken
    - Statement pooling: everything will probably be on fire anyway

It seems Rails uses advisory locks, with a config option to turn them off if e.g. you're using PgBouncer in transaction pooling mode

_\* Could be solved by using more than one connection? I.e. start transaction, take lock, if migration needs running then run migration on a different connection, end transaction._

## References

- [Rails: Running multiple migrations simultaneously can cause race conditions](https://github.com/rails/rails/issues/22092)
- [Rails: Allow Migration Advisory Locks to be disabled](https://github.com/rails/rails/issues/31190)

**Comment by tom-drake** [comment]
I came to the same conclusion around the `ACCESS EXCLUSIVE` lock and it makes more sense to use an advisory lock as you've said. From what I saw it should allow `runMigration` to stay mostly the same. I've not seen PgBouncer before, how would the transaction pooling be a problem? From what I can see in the discussion's you linked its because queries can be run in different sessions?

Would PgBouncer be a problem if this library is using node-pg with a single connection for its migrations?

**Comment by ThomWright** [comment]
Yes I think PgBouncer would be a problem. `node-pg` might have a single connection to PgBouncer, but PgBouncer could have multiple connections to Postgres itself. Each transaction might run on a different PgBouncer>Postgres connection.

**Comment by tom-drake** [comment]
Ok, so is the entire transaction run on a single connection even via PgBouncer? If so, would a `pg_advisory_xact_lock` type lock work? Instead of creating the lock at the start of the session we take the lock on every transaction and let it clean itself up after the commit. I'm still a little hazy on how PgBouncer deals with its connection pooling.

**Comment by ThomWright** [comment]
PgBouncer's three different pooling modes are documented here: https://pgbouncer.github.io/features.html

Session pooling will be fine, just not the others.

Taking an advisory lock on every transaction seems to have all of the disadvantages of using the `ACCESS EXCLUSIVE` lock but lacking the advantage of the lock being enforced by Postgres.

**Comment by tom-drake** [comment]
I think `pg_advisory_xact_lock` is a little different than just a regular advisory lock. It's true that its on the application to take the lock out but postgres should clean it up without the application needing to interfere. I don't think its a problem taking a lock on every transaction, it's not all that efficient but it's probably negligible compared to what is being executed via the migration scripts. This should work for pgBouncers transaction problems.

```
client.query("START TRANSACTION")
client.query("SELECT pg_advisory_xact_lock(1234)")
client.query(migration.sql)
...
client.query("COMMIT")
```

As an alternative, is support for pgBouncer something which is required?

**Comment by ThomWright** [comment]
I think support for PgBouncer is required, but that could be done simply by having an option to turn off the locking.

I think another advantage of keeping the lock outside of the transactions is that is ensures that all of the migrations that need to be done will be done by the same instance. That is, it removes the possibility of two competing instances of the application 'taking turns' when locks are released after each transaction. I'm not sure how likely this scenario is, but it seems like a desirable property to guarantee.

**Comment by tom-drake** [comment]
Ok, so I guess some clear documentation on the effects of using PgBouncer would be good then. In that case it would be recommended to use a single instance to migrate the database with the locking flag off.  Would you expect locking to be enabled by default and allow uses of PgBouncer to configure it off?

I think it would be fine having multiple instances migrating the database. It shouldn't matter if instance A runs migrations 1, 4 and 5 and instance B runs 2 and 3. They should all be atomic. It would only really be a problem if someone disables transactions but that might some documentation asking users to run a single instance to migrate.

**Comment by ThomWright** [comment]
Yep, documentation will be essential here I think. And yes, locking enabled by default.

There are common scenarios where transactions need to be disabled, e.g. `CREATE INDEX CONCURRENTLY`. I don't think we can avoid situations where people turn off the transaction for certain migrations. We do it sometimes, and our deployment strategy also means we sometimes get concurrent deployments. There's not much we can do about it.

It's true there shouldn't be any problems with the migration, I'm thinking it would just be easier to reason about. It would also be helpful to have all the logs for a migration run in a single place.

**Comment by tom-drake** [comment]
Sorry, been a little quiet on this issue. I will spend some time at the weekend and look at getting a PR together.

**Comment by ThomWright** [comment]
Oh no worries! I started working on it but haven't finished it. I'll try to revisit it and get it in a reasonable state at some point.
