### ISSUE TITLE
Typescript interface at odds with README.md

### ISSUE THREAD

**Issue by aegatlin** [ThomWright/postgres-migrations#32]
Awesome tool. I'm excited to try it.

The readme indicates that you can call migrate with only two arguments. But, the typescript interface for `3.0.2` is 

```typescript
  export function migrate(
    dbConfig: MigrateDBConfig,
    migrationsDirectory: string,
    config: Config,
  ): Promise<Migration[]>
```

If you want typescript users to use `migrate` as indicated in the docs, you could make config optional, `config?: Config`.

**Comment by ThomWright** [comment]
Thanks, I reckon the docs have needed a once-over since the move to TypeScript. I'll have a look through and fix them up.

**Comment by ThomWright** [comment]
Should be solved with the new TypeScript changes and README updates.
