### ISSUE TITLE
Installed version of pg client is not compatible with node 14

### ISSUE THREAD

**Issue by maximilian-krauss** [ThomWright/postgres-migrations#42]
Hey,

I just spent an hour debugging and want to avoid that you have to do the same 😅  It looks like there was an error with node 14 and versions < `8.0.3` of pg.
It just stops after `connecting...` and does nothing. I fixed it by providing the latest version of pg to the migration client but you might want to update `pg` to `8.0.3` if you target node 14 in the future.

Thanks by the way for this cool package 🎉 

Cheers,
Max

**Comment by ThomWright** [comment]
Thanks for this. I'll have a look. It _seems_ like a safe-ish change, but I'm not sure if it requires a major version bump of this library.

**Comment by ThomWright** [comment]
Changelog for pg: https://github.com/brianc/node-postgres/blob/master/CHANGELOG.md#pg800

It's the `ssl` settings I'm most concerned about being breaking.

I would accept a PR though, then I can decide what version to publish :)

**Comment by maximilian-krauss** [comment]
Hey :)
PR is open. True thing about that SSL change, that could really lead to unexpected behavior though 🥺 
Since node 14 is not LTS yet, I would also understand that you might want to postpone that a little.

Cheerio,
Max

**Comment by eamonnmcevoy** [comment]
Thanks for this post.

Just spent a whole day trying to figure out why the db deployment failed when i ran it in a node docker container. Downgraded the base image from `node:14-alpine` to `node:13-alpine` and it works.
