### ISSUE TITLE
Down migrations

### ISSUE THREAD

**Issue by jlippold** [ThomWright/postgres-migrations#46]
How do you test a migration in development without a down script? 

Lets say I'm adding a new constraint to a table and dropping a column in a table.

I add the new constraint in a migration and run it against local db.
Then I make a new migration to drop a column, because I can't add the drop column statement to previous migration ( no down sql ) and run it against local db. 
Then since I'm a dummy, I realize the constraint I added was incorrect. So I have to commit a new migration again to fix it?

Then maybe I want to rebase all of these migrations into one, and verify that it works. Would I have to reset my DB to zero in order to test it against the original db schema.

I hope this isn't a dumb question, it just not apparent to me after reading the readme. 

Thanks for the help

**Comment by ThomWright** [comment]
If it's local development, you can just connect to the database and:

- undo the migration you want to change
- delete the row from the migration table

Does this help?
