### ISSUE TITLE
Add support for typescript migration files

### ISSUE THREAD

**Issue by ravshansbox** [ThomWright/postgres-migrations#50]

**Comment by ThomWright** [comment]
Hello

A bit more context would be useful. Why is compiling the TS yourself not an acceptable solution? Have you tried it? Were there problems?

Also, are you sure you really want the whole TypeScript compiler bundled in with a library for doing database migrations?

Realistically I'm not planning to support this, so I'm going to close this for now.

**Comment by ravshansbox** [comment]
@ThomWright, it's for development time purposes.
1. One wouldn't like to write migrations in JavaScript if whole codebase is in TypeScript.
2. Using TypeScript does not mean it will be bundled in with a library. You only need to discover .ts files as migration files, when you require it, there will already be typescript loader running, it will do the rest.
