### ISSUE TITLE
Run some migrations only for test purpuse

### ISSUE THREAD

**Issue by khalilou88** [ThomWright/postgres-migrations#54]
Hi, 

Thanks for this lib.
I use migrations for my database.
For tests it's also useful to init my database before running tests in a  docker container.
Some tests need to insert some fake data before executing it, like a login test. In liquibase word, we have the ability to add some migration only for test, dev, prod environments.
 
Maybe what I am asking for it is not good practice to keep migrations clean.

So I like to hear from you and floks what do you think?

**Comment by ThomWright** [comment]
You can do that without help from this library, and I would suggest that would be the better approach!

**Comment by khalilou88** [comment]
thanks for your reply.
I choose to insert data from sql script with the help of testcontainers-node before running tests.

you can close this issue.
Thanks
