### ISSUE TITLE
Executed_at  with timezone

### ISSUE THREAD

**Issue by khalilou88** [ThomWright/postgres-migrations#55]
Hello,

If my understanding of datetime in postgressql is good, I think Executed_at field should be with time zone and with UTC by default.
something like that :
**executed_at  timestamptz NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')**

Imagine I run a migration and  I changed the timezone of the database server then I run another migration...

Thanks

**Comment by ThomWright** [comment]
It's a good question. There are a few things to unpack here.

1. In your example: `executed_at timestamptz NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')` the `AT TIME ZONE 'UTC'` is redundant. It doesn't matter what timezone `now()` returns, it will always be the same instant in time. `timestamptz` looks at the timezone information, so will store the same instant regardless of what timezone is returned by `now()`.

2. `current_timestamp` and `now()` return the same time - the time at the start of the transaction. [See here](https://www.postgresql.org/docs/9.6/functions-datetime.html#FUNCTIONS-DATETIME-CURRENT).

That said, I think you are correct that the type _should_ be `timestamptz`, not `timestamp`. `timestamp` effectively throws away the timestamp information, from what I understand. So, if you change the timezone of the server, the times stored before and after the change will be... well, from different timezones, but the data won't reflect that.

I'm surprised to see `timezone` used here. I use `timestamptz` pretty much exclusively nowadays, especially for e.g. `created_at`-style columns.

Generally I would recommend that your database be configured to use UTC. But yes, maybe that isn't possible for some people, and yes, this is still an issue. 

Also, the `executed_at` is not used internally, it's mainly there to help e.g. debugging. Worst case: the times look a bit odd if people are doing timezone configuration changes in their database. Unless someone is using that column for something I don't expect, I don't see this as a _huge_ issue.

Finally, this is quite a difficult issue to solve. Changing the initial migration, and the structure of the `migrations` table, is not backwards compatible. I'm not sure what the best way to fix this would be.
