### ISSUE TITLE
Scan subfolders for migrations [FEATURE REQUEST]

### ISSUE THREAD

**Issue by kerekes** [ThomWright/postgres-migrations#63]
I want to provide migrations in a nested folder structure, e.g.

```
./migrations/common/1_create_tables.sql
./migrations/common/2_create_functions.sql
./migrations/common/4_add_created_column.sql
./migrations/test/3_insert_test_data.sql
```

On a development environment I would tell postgres-migrations to load migrations from `./migrations/common` (so only three migrations are executed), whereas in a development environment I override the folder with `./migrations/` (so that all four migrations in the example above would be executed).

Would this be a bad idea for postgres-migrations?

**Comment by ThomWright** [comment]
Personally, I don't think this will work for this project. It violates some of basic principles around dev/prod parity and consecutive ordering.

Instead, I advise you to manage your test data separately to the migration system. In general, and are probably exceptions, I would recommend using this library for _schema migrations_ only, and maybe some static data.
