### ISSUE TITLE
How to incorporate ".ts" migrations?

### ISSUE THREAD

**Issue by cakoose** [ThomWright/postgres-migrations#69]
My setup:
- ".sql" and ".ts" migration files in "src/migrations"
- `tsc` compiles all ".ts" files under "src" and outputs ".js" files to "dist".

How do I invoke postgres-migrations' `migrate` function?  I want it to pick up ".sql" files from "src/migrations" and ".js" files from "dist/migrations".

One potential hack is to make our build/watch process copy the ".sql" files into "dist" as well.  But I'd like to avoid that if possible.

**Comment by ThomWright** [comment]
You'll need to make your build put the JS and SQL files in the same directory, wherever that is, and point `postgres-migrations` at that directory.

Sorry, I'm not going to write your build for you! :wink:

**Comment by cakoose** [comment]
I'm not asking you to write my build for me.

It's not that hard to copy the ".sql" files in my one-shot build scripts.  But like many people, I use `tsc --watch` for incremental recompilation in development, and that doesn't seem to have a way to copy ".sql" files.  It would be nice if postgres-migrations supported that use case.

(And in general, I'm not sure if "just point postgres-migrations at the JS files" works for TS.  For example, for the hash of the migration, I think it might be better to use the hash of the TS file rather than the JS file.)

**Comment by ThomWright** [comment]
OK, glad you got it to work.

Honestly, supporting JS-generated migrations is probably my biggest regret in this library!

**Comment by cakoose** [comment]
Oh sorry, to be clear, I only meant to cross out the parenthetical comment.

I'm still not sure how to deal with TS migrations when using `tsc --watch`.

**Comment by ThomWright** [comment]
>One potential hack is to make our build/watch process copy the ".sql" files into "dist" as well. But I'd like to avoid that if possible.

Why? That sounds like exactly what a build should do.
