### ISSUE TITLE
How to update comments of existing migration script?

### ISSUE THREAD

**Issue by wongjiahau** [ThomWright/postgres-migrations#76]
When I tried to update the comments of existing migration script, I will get the `hash not match` error, so I wondering if there's a way to just generate hash from significant character without including comments?

**Comment by ThomWright** [comment]
If you have a file e.g. `001_my-migration.sql` then you can create another file `001_my-migration.md` and put any docs in there. This file is mutable, and ignored by the library.

**Comment by wongjiahau** [comment]
thanks, I think it will be great if you can include this tips in the readme.

**Comment by ThomWright** [comment]
I quickly added an example. Could do better, but that'll do for now.

**Comment by wongjiahau** [comment]
I actually found a better way, which is to use [comment statements](https://www.postgresql.org/docs/9.1/sql-comment.html).

Example,
```psql
COMMENT ON COLUMN my_table.my_column IS '
Employee ID number.
Example, 1234
';

```

**Comment by ThomWright** [comment]
If that works for you then great :slightly_smiling_face:
