### ISSUE TITLE
No way to specify a migration table name

### ISSUE THREAD

**Issue by jbelelieu** [ThomWright/postgres-migrations#78]
I'm currently working on a project that has multiple schemas within an instance of Postgres. Multiple different services will be using the instance, each with their own schema. Presently the migrations table is hard coded in `migrate.js` (line 84) and doesn't allow for a custom schema input or table name, meaning that if multiple services all use this, they'll all be sharing the same public.migrations table, which isn't ideal.

It would be highly useful if the extra `config` object that's passed into the `migrate` function could accept a custom schema name and table name, which would then be passed into the hardcoded `migrationTableName` variable in the `runMigrations` function.

**Comment by ThomWright** [comment]
Did you search for existing issues to do with schemas?

https://github.com/ThomWright/postgres-migrations/issues?q=schema+

**Comment by jbelelieu** [comment]
People skills 10/10. I'll fork your project and do it myself.
