### ISSUE TITLE
What purpose does the hash serve?

### ISSUE THREAD

**Issue by altaurog** [ThomWright/postgres-migrations#83]
This isn’t a bug, it’s a question.  I just want to understand what the function of the hashes is, exactly.  I understand that storing the hash of the migration allows me to confirm that the hash has not changed, but each migration runs only once against any given db, so by the time I am checking the hash, I will not be running the migration again, and if I run it on a fresh db, I don’t have the hash.
Is this just a best-effort attempt to protect the db history record by flagging changes to the migrations (when we run the next migration against the original db), or is there more to it than that?

Observation: It seems that there’s sort of an ‘impedance mismatch’ between git, which always allows changes even to history, and migrations, which should not be changed, but the hashing doesn’t provide a very complete solution.  If we were running these migrations against multiple databases and we were really concerned about ensuring they don’t change, we’d probably want to store the hash somewhere outside the db when the migration is run and then check the migration hashes in a separate CI step on each push thereafter, or just store the migration itself in less mutable storage (like a versioned s3 bucket with object lock).

Am I missing something?

**Comment by ThomWright** [comment]
>Is this just a best-effort attempt to protect the db history record by flagging changes to the migrations (when we run the next migration against the original db), or is there more to it than that?

In a word: yes!

It helps prevent accidental changes to migration files. It's useful in case someone modifies a file expecting the change to have some effect, perhaps not realising that the migration has already been applied. The files are not intended to change, so if someone changes something it's helpful to tell them that something unexpected has happened.

>we’d probably want to store the hash somewhere outside the db when the migration is run and then check the migration hashes in a separate CI step on each push thereafter, or just store the migration itself in less mutable storage (like a versioned s3 bucket with object lock)

I don't think I understand why one would do this. It seems like overkill to me. What scenario are you protecting against here, and why do you think this is a problem worth solving?

**Comment by altaurog** [comment]
> I don't think I understand why one would do this. It seems like overkill to me. What scenario are you protecting against here, and why do you think this is a problem worth solving?

I understand in many circumstances it might be overkill.  To my mind, there would be two motivations for doing this:
1. We want to ensure the migrations are not modified before they are applied to other databases, not after the next migration is applied to the first database.
2. Ensuring certain files don’t change isn’t per-se the job of the migration tool

This isn’t meant at all as a suggestion for postgres-migrations, just my observation about how I might approach the issue to address the above concern.  In any case, thanks so much for confirming my understanding!
