### ISSUE TITLE
Missing SQL query wrapper

### ISSUE THREAD

**Issue by technic** [ThomWright/postgres-migrations#86]
I think using SQL params or query wrapper here is better than plain string interpolation

https://github.com/ThomWright/postgres-migrations/blob/dbfc5ccd7c71d77c24200d403cd72722017eca67/src/migrate.ts#L169

**Comment by ThomWright** [comment]
Yeah, it's a very reasonable point.

The justification here is that this isn't user input. It's a hardcoded value within the library.

See here:

https://github.com/ThomWright/postgres-migrations/blob/dbfc5ccd7c71d77c24200d403cd72722017eca67/src/migrate.ts#L112


There might be a better way to make this obvious though.

**Comment by technic** [comment]
Ah, it's a table name. Yep it's problematic to escape it with usual tools.
